//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comuna
    {
        public Comuna()
        {
            this.Sucursal = new HashSet<Sucursal>();
        }
    
        public string Codigo { get; set; }
        public string CodigoR { get; set; }
        public string Nombre { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
    }
}
