//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrada
    {
        public Entrada()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public string NBoleto { get; set; }
        public Nullable<int> NFun { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual ICollection<Venta> Venta { get; set; }
        public virtual Funcion Funcion { get; set; }
    }
}
