//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estreno
    {
        public Estreno()
        {
            this.Funcion = new HashSet<Funcion>();
        }
    
        public string Id { get; set; }
        public string DescripcionE { get; set; }
    
        public virtual ICollection<Funcion> Funcion { get; set; }
    }
}
