//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcion
    {
        public Funcion()
        {
            this.Entrada = new HashSet<Entrada>();
        }
    
        public int Codigo { get; set; }
        public string NombreF { get; set; }
        public Nullable<int> CodPel { get; set; }
        public string SalaId { get; set; }
        public string Estreno { get; set; }
        public string Dia { get; set; }
        public string HoraI { get; set; }
        public string HoraT { get; set; }
    
        public virtual ICollection<Entrada> Entrada { get; set; }
        public virtual Estreno Estreno1 { get; set; }
        public virtual Pelicula Pelicula { get; set; }
        public virtual Sala Sala { get; set; }
    }
}
