//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public Pelicula()
        {
            this.Funcion = new HashSet<Funcion>();
        }
    
        public int IdPelicula { get; set; }
        public string NombreP { get; set; }
        public string Genero { get; set; }
        public string Idioma { get; set; }
        public string Director { get; set; }
        public string Sinopsis { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual ICollection<Funcion> Funcion { get; set; }
        public virtual Gene Gene { get; set; }
        public virtual Idioma Idioma1 { get; set; }
    }
}
