//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.Sala = new HashSet<Sala>();
        }
    
        public string CodigoCine { get; set; }
        public string NombreS { get; set; }
        public string Direccion { get; set; }
        public string Comuna { get; set; }
    
        public virtual Comuna Comuna1 { get; set; }
        public virtual ICollection<Sala> Sala { get; set; }
    }
}
