//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public Tipo()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public string Codigo { get; set; }
        public string DescripcionT { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
