//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vistas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CineVEntities : DbContext
    {
        public CineVEntities()
            : base("name=CineVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Comuna> Comuna { get; set; }
        public DbSet<Entrada> Entrada { get; set; }
        public DbSet<Estreno> Estreno { get; set; }
        public DbSet<Funcion> Funcion { get; set; }
        public DbSet<Gene> Gene { get; set; }
        public DbSet<Idioma> Idioma { get; set; }
        public DbSet<Pelicula> Pelicula { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<Sala> Sala { get; set; }
        public DbSet<Sucursal> Sucursal { get; set; }
        public DbSet<Tipo> Tipo { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Venta> Venta { get; set; }
    }
}
